language: minimal
os: linux
dist: xenial
services:
    - docker

before_install:
    - docker build -t brianwebb01/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true brianwebb01/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-us-east-1-864051287342"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY