language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t brianwebb01/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true brianwebb01/docker-react npm run test